/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module asel_53 (
    input asel_signal,
    input [15:0] cu_data,
    input [15:0] ra_data,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    if (asel_signal) begin
      out = cu_data;
    end else begin
      out = ra_data;
    end
  end
endmodule
