/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module btn_list_58 (
    input btnr0c0,
    input btnr0c1,
    input btnr0c2,
    input btnr0c3,
    input btnr1c0,
    input btnr1c1,
    input btnr1c2,
    input btnr1c3,
    input btnr2c0,
    input btnr2c1,
    input btnr2c2,
    input btnr2c3,
    input btnr3c0,
    input btnr3c1,
    input btnr3c2,
    input btnr3c3,
    output reg [15:0] btn_list
  );
  
  
  
  always @* begin
    btn_list = {btnr3c3, btnr3c2, btnr3c1, btnr3c0, btnr2c3, btnr2c2, btnr2c1, btnr2c0, btnr1c3, btnr1c2, btnr1c1, btnr1c0, btnr0c3, btnr0c2, btnr0c1, btnr0c0};
  end
endmodule
